In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
df=pd.read_excel('data_for_eda.xlsx')
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
dtypes: int64(1), str(10)
memory usage: 918.2 KB

In [8]:
df.head(2)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662

In [12]:
df['Date']=df['Date_of_Journey'].str.split('/').str[0]
df['Month']=df['Date_of_Journey'].str.split('/').str[1]
df['Year']=df['Date_of_Journey'].str.split('/').str[2]
df['Date']=df['Date'].astype(int)
df['Month']=df['Month'].astype(int)
df['Year']=df['Year'].astype(int)

In [19]:
df.drop('Date_of_Journey',axis=1, inplace=True )

KeyError: "['Date_of_Journey'] not found in axis"

In [20]:
df.head(1)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019

In [46]:
df['Duration_Hour']=(df['Duration'].str.extract(r'(\d+)h').fillna(0).astype(int))
df['Duration_Min']=(df['Duration'].str.extract(r'(\d+)m').fillna(0).astype(int))
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Source           10683 non-null  str
 2   Destination      10683 non-null  str
 3   Route            10682 non-null  str
 4   Dep_Time         10683 non-null  str
 5   Arrival_Time     10683 non-null  str
 6   Duration         10683 non-null  str
 7   Total_Stops      10682 non-null  str
 8   Additional_Info  10683 non-null  str
 9   Price            10683 non-null  int64
 10  Date             10683 non-null  int64
 11  Month            10683 non-null  int64
 12  Year             10683 non-null  int64
 13  Duration_Hour    10683 non-null  int64
 14  Duration_Min     10683 non-null  int64
dtypes: int64(6), str(9)
memory usage: 1.2 MB

In [50]:
df.drop(('Duration'),axis=1, inplace=True)

In [54]:
df.duplicated().sum()

np.int64(0)

In [55]:
df.drop_duplicates(inplace=True)
df.head(2)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Total_Stops,Additional_Info,Price,Date,Month,Year,Duration_Hour,Duration_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,non-stop,No info,3897,24,3,2019,2,50
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,2 stops,No info,7662,1,5,2019,7,25

In [59]:
df['Dep_Time'].astype=(int)

In [70]:
df['Arrival_Time']=df['Arrival_Time'].apply(lambda x:x.split(' ')[0])
df['Arrival_Hour']=df['Arrival_Time'].str.split(':').str[0]
df['Arrival_Minn']=df['Arrival_Time'].str.split(':').str[1]

KeyError: 'Arrival_Time'

In [71]:
df.drop('Arrival_Time', axis=1, inplace=True)
df.head(20)

KeyError: "['Arrival_Time'] not found in axis"

In [79]:
df['Arrival_Minn'].apply(lambda x: x.split(' ')[0])

0        10
1        15
2        25
3        30
4        35
         ..
10678    25
10679    20
10680    20
10681    10
10682    15
Name: Arrival_Minn, Length: 10463, dtype: str

In [80]:
df.head(2)

,Airline,Source,Destination,Route,Dep_Time,Total_Stops,Additional_Info,Price,Date,Month,Year,Duration_Hour,Duration_Min,Arrival_Hour,Arrival_Minn
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,non-stop,No info,3897,24,3,2019,2,50,01,10 22 Mar
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,2 stops,No info,7662,1,5,2019,7,25,13,15

In [81]:
df['Dep_Hour']=df['Dep_Time'].str.split(':').str[0]
df['Dep_Min']=df['Dep_Time'].str.split(':').str[1]

In [82]:
df.drop('Dep_Time', axis=1, inplace=True)

In [85]:
df['Dep_Hour']=df['Dep_Hour'].astype(int)
df['Dep_Min']=df['Dep_Min'].astype(int)

In [90]:
df.head(2)

,Airline,Source,Destination,Route,Total_Stops,Additional_Info,Price,Date,Month,Year,Duration_Hour,Duration_Min,Arrival_Hour,Arrival_Minn,Dep_Hour,Dep_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,non-stop,No info,3897,24,3,2019,2,50,1,10 22 Mar,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2 stops,No info,7662,1,5,2019,7,25,13,15,5,50

In [88]:
df['Arrival_Hour']=df['Arrival_Hour'].astype(int)

In [94]:
df['Total_Stops'].unique()

<StringArray>
['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops']
Length: 6, dtype: str

In [95]:
df['Total_Stops']=df['Total_Stops'].map({'non-stop':0, '1 stops':1, '2 stops':2, '3 stops': 3, '4 stops':4, np.nan: 1})

In [96]:
df.head(2)

,Airline,Source,Destination,Route,Total_Stops,Additional_Info,Price,Date,Month,Year,Duration_Hour,Duration_Min,Arrival_Hour,Arrival_Minn,Dep_Hour,Dep_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,0.0,No info,3897,24,3,2019,2,50,1,10 22 Mar,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2.0,No info,7662,1,5,2019,7,25,13,15,5,50

In [97]:
df['Price']=df['Price'].astype(float)

In [100]:
df.drop('Arrival_Minn',axis=1, inplace=True)

In [99]:
pip install scikit-learn

^C
Note: you may need to restart the kernel to use updated packages.