In [50]:
import seaborn as sns 
df=sns.load_dataset('tips')

In [51]:
df.drop(columns=["day"], index=1, inplace=True)

In [52]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'time', 'size'], dtype='str')

In [53]:
x=df[['total_bill', 'tip', 'sex', 'smoker','size']]
y=df['time']

In [54]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.3, random_state=0)

x_train.head()

     total_bill   tip     sex smoker  size
62        11.02  1.98    Male    Yes     2
117       10.65  1.50  Female     No     2
53         9.94  1.56    Male     No     2
67         3.07  1.00  Female    Yes     1
27        12.69  2.00    Male     No     2

In [55]:
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
le2=LabelEncoder()
le3=LabelEncoder()

In [56]:
x_train['sex']=le1.fit_transform(x_train['sex'])
x_train['smoker']=le2.fit_transform(x_train['smoker'])
y_train=le3.fit_transform(y_train)

In [57]:
x_test['sex']=le1.transform(x_test['sex'])
x_test['smoker']=le2.transform(x_test['smoker'])
y_test=le3.transform(y_test)

In [58]:
x_train.head()

     total_bill   tip  sex  smoker  size
62        11.02  1.98    1       1     2
117       10.65  1.50    0       0     2
53         9.94  1.56    1       0     2
67         3.07  1.00    0       1     1
27        12.69  2.00    1       0     2

In [59]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(x_train, y_train)
y_pred=gnb.predict(x_test)

In [63]:
from sklearn.metrics import accuracy_score,confusion_matrix, classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.7945205479452054
[[55  1]
 [14  3]]
              precision    recall  f1-score   support

           0       0.80      0.98      0.88        56
           1       0.75      0.18      0.29        17

    accuracy                           0.79        73
   macro avg       0.77      0.58      0.58        73
weighted avg       0.79      0.79      0.74        73